### ISSUE TITLE
segment analysis: several links missing after completion 

### ISSUE THREAD

**Issue by yyoyochen** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#165]
Hi,

I'm having an issue with missing links after completing segment analysis.
The original map used as input is in green, and results from segment analysis in purple.
I've tried performing the same analysis with depthmapX and don't have such problem.
Are there any suggestion of what might be the cause?
![image](https://user-images.githubusercontent.com/33952749/33202177-7565d950-d136-11e7-89ac-adc5740d085b.png)

**Comment by jorgegil** [comment]
Have you checked the "road centre line or segment map" box below the map layer selection?

The default analysis assumes the map is an axial map (2 nodes per line) and therefore only sends the first and second node of a line to depthmapX for analysis.
If you indicate that it's a road centre line, then it will send all segments of the polyline separately.

If you analyse a road centre line in depthmapX, you must take care to NOT convert it to an axial map first, otherwise it will add many more segments to the map. The results that you report from depthmapX might look ok but be wrong as well...

**Comment by yyoyochen** [comment]
Thanks for the advice! I marked the "road centre line or segment map" box and applied the analysis successfully. Thank you for your support, and the awesome tool!
