### ISSUE TITLE
QGIS 3

### ISSUE THREAD

**Issue by ugosantana** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#170]
Hi Jorge and everyone,

Can't see the toolkit on the qgis 3 repository, only on qgis 2. Is there any way to install it on qgis 3 on a mac?

Thanks

Ugo

**Comment by jorgegil** [comment]
The SST is not yet available for QGIS 3, as is the case for many other plugins. The plugin needs to be adapted and modified in order to work in the new QGIS 3.

I'm waiting for the QGIS 3 LTR (Long Term Release) later this year, which is a stable version with support and updates for 2 years.

In the mean time, I recommend users to continue using QGIS 2.18 LTR.

**Comment by nirvn** [comment]
@jorgegil , any update on the port to QGIS 3 now that QGIS 2.18 has reached its EOL? Cheers.
