### ISSUE TITLE
depthMapXremote not activated in QGIS

### ISSUE THREAD

**Issue by yogitakarale** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#175]
I am just getting started with using qgis space syntax plugin.
I have installed depthMapX as suggested in user guide. However, when I try to use graph analysis functionality, depthMapXRemote option doe not activate. Attached is the screenshot.
![image](https://user-images.githubusercontent.com/13227974/54801396-a9113b80-4c34-11e9-9579-4ca97389009d.png)

**Comment by jorgegil** [comment]
You need depthmapXnet, please follow the download link at the bottom of the window and make sure it is running.
Then you also need a network layer that in a projected CRS. Since no entry appears in the Layer drop down menu I assume there is no valid layer available. Or you simply haven't selected a map layer to analyse.

Jorge
