### ISSUE TITLE
Meaning of radius and result of analysis is all blue

### ISSUE THREAD

**Issue by Nolty8** [SpaceGroupUCL/qgisSpaceSyntaxToolkit#185]
Hello.

I have some question.
1)Users input radius on depthmapX remote tab,what does that mean? I mean, what's changed when I input another values?
   I know that generally n or 3 is used as radius from researches about space syntax.

2)I analyzed my data(downloaded from openstreetmap), checked "segment map or road center line" and selected segment.
   But the result map was all blue (on classic). What do you think is the reasons? The map is too complicated or not cleaned well?
   I excluded lines whose types were motorway and motorway link.

I'm sorry for my poor English.

**Comment by jorgegil** [comment]
@Nolty8 for this sort of general space syntax questions and usage (not an issue with the tool) I recommend you post the question to the space syntax toolkit mailing list: https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=SPACESYNTAX-TOOLKIT

It is strongly advised that you read up some manuals about space syntax methods before you try to run, let alone interpret analysis results.

If the map is all blue is probably because the analysis parameters that you chose were incorrect (for example 3 as a radius in segment analysis does not make sense); or the map is not correct (a OSM map needs to go through some steps and checks to be ready for use). But it might be the first option: the radius is an analysis cut-off distance, in segment analysis the default unit is metres; in axial analysis the radius is topological (3 steps).

There are some tutorials and sample data in the documents folder of this repository that might help you get started:
https://github.com/SpaceGroupUCL/qgisSpaceSyntaxToolkit/tree/master/documents

**Comment by Nolty8** [comment]
Dear Mr.Gil.

Thank you for your replying, sir.

Of course I read most of the tutorials in the documents folder and did analysis with the sample data, but I failed on detail parts that are not in the tutorials.
Anyway I'll restart with the mailing list, thank you.
